In [ ]:
import torch

In [ ]:
x = torch.Tensor(2,3,4)

In [ ]:
x.requires_grad

False

In [ ]:
x.requires_grad = True

In [ ]:
x.requires_grad

True

In [ ]:
x = torch.arange(3, dtype=torch.float32, requires_grad=True)
print(x)

tensor([0., 1., 2.], requires_grad=True)


In [ ]:
a = x + 2
b = a ** 2
c = b + 3
y = c.mean()
print(y)

tensor(12.6667, grad_fn=<MeanBackward0>)


In [ ]:
y.grad_fn

In [ ]:
y.backward()

x.grad

In [ ]:
torch.cuda.is_available()

True

In [ ]:
x = torch.Tensor(2,3)

In [ ]:
x.device

device(type='cpu')

In [ ]:
torch.device("cpu")

device(type='cpu')

In [ ]:
torch.device("cuda")

device(type='cuda')

In [ ]:
x.to(torch.device("cuda"))

tensor([[5.2643e-35, 0.0000e+00, 2.6667e+00],
        [0.0000e+00,        nan, 0.0000e+00]], device='cuda:0')

In [ ]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [ ]:
device

device(type='cuda')

In [ ]:
x = x.to(device)

In [ ]:
x =  torch.Tensor(2,3)

In [ ]:
x.numpy()

array([[1.2946401e+11, 0.0000000e+00, 0.0000000e+00],
       [0.0000000e+00, 1.4012985e-45, 0.0000000e+00]], dtype=float32)

In [ ]:
x = torch.Tensor(2,3).to(device)

In [ ]:
x.numpy()

TypeError: ignored

In [ ]:
x.cpu().numpy()

In [ ]:
x = torch.Tensor(2,3)

In [ ]:
x.requires_grad =  True

In [ ]:
x.numpy()

In [ ]:
x.detach().numpy()

In [ ]:
import torch
dimensions = [784,100,10]
N_batch = 64

In [ ]:
X = torch.randn(dimensions[0], N_batch)
y = torch.randn(dimensions[-1], N_batch)

In [ ]:
W1 = torch.randn(100, 784, requires_grad = True)
b1 = torch.ones(100, 1, requires_grad = True)
W2 = torch.randn(10, 100, requires_grad = True)
b2 = torch.ones(64, requires_grad = True)

In [ ]:
Z1 = torch.add(torch.mm(W1, X), b1)
A1 = torch.relu(Z1)
Z2 = torch.add(torch.mm(W2, A1), b2)
A2 = torch.relu(Z2)

In [ ]:
A2.shape

torch.Size([10, 64])

In [ ]:

loss = (torch.mean(A2, 1, True) - y)**2
loss = loss.mean()


In [ ]:
loss.backward()

In [ ]:
lr = 5e-6

In [ ]:
with torch.no_grad():
      W1 -= loss * lr
      b1 -= loss * lr
      W2 -= loss * lr
      b2 -= loss * lr
      
      W1.grad.zero_()
      W2.grad.zero_()
      b1.grad.zero_()
      b2.grad.zero_()

In [ ]:
epochs = 600

In [ ]:
W1 = torch.randn(100, 784, requires_grad = True)
b1 = torch.ones(100, 1, requires_grad = True)
W2 = torch.randn(10, 100, requires_grad = True)
b2 = torch.ones(64, requires_grad = True)

In [ ]:
for epoch in range(epochs):
    Z1 = torch.add(torch.mm(W1, X), b1)
    A1 = torch.relu(Z1)
    Z2 = torch.add(torch.mm(W2, A1), b2)
    A2 = torch.relu(Z2)

    loss = (torch.mean(A2, 1, True) - y)**2
    loss = loss.mean()  
    loss.backward()

    if epoch % 50 == 0:
      print(loss)

    with torch.no_grad():
        W1 -= loss * lr
        b1 -= loss * lr
        W2 -= loss * lr
        b2 -= loss * lr
        W1.grad.zero_()
        W2.grad.zero_()
        b1.grad.zero_()
        b2.grad.zero_()

tensor(19529.9102, grad_fn=<MeanBackward0>)
tensor(171.5832, grad_fn=<MeanBackward0>)
tensor(86.7991, grad_fn=<MeanBackward0>)
tensor(57.1479, grad_fn=<MeanBackward0>)
tensor(42.6680, grad_fn=<MeanBackward0>)
tensor(34.2800, grad_fn=<MeanBackward0>)
tensor(28.3542, grad_fn=<MeanBackward0>)
tensor(23.9589, grad_fn=<MeanBackward0>)
tensor(20.7192, grad_fn=<MeanBackward0>)
tensor(18.7973, grad_fn=<MeanBackward0>)
tensor(17.2710, grad_fn=<MeanBackward0>)
tensor(15.9299, grad_fn=<MeanBackward0>)
