In [ ]:
import numpy as np
import torch

In [ ]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data.shape

torch.Size([2, 2])

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
x_ones = torch.ones_like(x_np)

In [ ]:
x_rand = torch.rand_like(x_data, dtype=torch.float)

In [ ]:
tensor = torch.rand(3,4)
tensor.shape

torch.Size([3, 4])

In [ ]:
tensor.dtype

torch.float32

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
tensor = torch.rand(4, 4)
print(f"Pierwszy wiersz: {tensor[0]}")
print(f"Pierwsza kolumna: {tensor[:, 0]}")
print(f"Ostatnia kolumna: {tensor[..., -1]}")
tensor[:,1] = 0 
print(tensor)

Pierwszy wiersz: tensor([0.4719, 0.1412, 0.3370, 0.9106])
Pierwsza kolumna: tensor([0.4719, 0.9894, 0.6388, 0.6654])
Ostatnia kolumna: tensor([0.9106, 0.8577, 0.1948, 0.0932])
tensor([[0.4719, 0.0000, 0.3370, 0.9106],
        [0.9894, 0.0000, 0.4414, 0.8577],
        [0.6388, 0.0000, 0.6673, 0.1948],
        [0.6654, 0.0000, 0.3346, 0.0932]])


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0.4719, 0.0000, 0.3370, 0.9106, 0.4719, 0.0000, 0.3370, 0.9106, 0.4719,
         0.0000, 0.3370, 0.9106],
        [0.9894, 0.0000, 0.4414, 0.8577, 0.9894, 0.0000, 0.4414, 0.8577, 0.9894,
         0.0000, 0.4414, 0.8577],
        [0.6388, 0.0000, 0.6673, 0.1948, 0.6388, 0.0000, 0.6673, 0.1948, 0.6388,
         0.0000, 0.6673, 0.1948],
        [0.6654, 0.0000, 0.3346, 0.0932, 0.6654, 0.0000, 0.3346, 0.0932, 0.6654,
         0.0000, 0.3346, 0.0932]])


In [ ]:
y1 = tensor @ tensor.T
print(tensor.T)
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[0.4719, 0.9894, 0.6388, 0.6654],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.3370, 0.4414, 0.6673, 0.3346],
        [0.9106, 0.8577, 0.1948, 0.0932]])


tensor([[1.1654, 1.3966, 0.7037, 0.5116],
        [1.3966, 1.9094, 1.0937, 0.8860],
        [0.7037, 1.0937, 0.8914, 0.6665],
        [0.5116, 0.8860, 0.6665, 0.5634]])

In [ ]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)


tensor([[0.2227, 0.0000, 0.1135, 0.8292],
        [0.9790, 0.0000, 0.1948, 0.7357],
        [0.4081, 0.0000, 0.4454, 0.0379],
        [0.4427, 0.0000, 0.1120, 0.0087]])

In [ ]:
t = torch.ones(5)
n = t.numpy()

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
t = torch.rand((5, 2))
t.reshape(-1)

tensor([0.4173, 0.7705, 0.4133, 0.1293, 0.0827, 0.1026, 0.9121, 0.5098, 0.1305,
        0.0312])

In [ ]:
Z = np.vander([1, 2, 3, 5], 4)
Z

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [ ]:
A = torch.ones_like(torch.empty(4, 7))
B = torch.rand_like(A)
C = torch.tensor(range(2, 21, 2))
D = torch.from_numpy(Z)
print(A)
print(B)
print(C)
print(D)

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])
tensor([[0.2497, 0.1603, 0.5724, 0.6149, 0.7945, 0.6281, 0.4579],
        [0.1883, 0.6703, 0.1602, 0.1670, 0.7397, 0.2789, 0.8374],
        [0.9740, 0.2990, 0.1595, 0.1380, 0.9037, 0.1138, 0.1970],
        [0.5501, 0.3067, 0.2961, 0.0666, 0.2709, 0.7960, 0.3980]])
tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
tensor([[  1,   1,   1,   1],
        [  8,   4,   2,   1],
        [ 27,   9,   3,   1],
        [125,  25,   5,   1]])


$$D = A \cdot B + C$$

In [ ]:
A = torch.tensor([[2, 4], [5, 7]])
B = torch.tensor([[1, 1], [2, 3]])
C = torch.tensor([[10, 10], [12, 1]])

D = torch.add(torch.matmul(A, B), C)
D

tensor([[20, 24],
        [31, 27]])

In [ ]:
A = torch.tensor([[1, 2], [1, 1]])
B = torch.tensor([[1, 2, 3], [3, 2, 1]])

A = torch.sum(A, 0)
B = torch.sum(B)
C = A * B
C

tensor([24, 36])

In [ ]:
A = torch.tensor([[5, -2], [10, 41]])

B = torch.stack((torch.tensor(range(4)), torch.cat((A[0], A[1]), 0)))
B = B.t()
B

tensor([[ 0,  5],
        [ 1, -2],
        [ 2, 10],
        [ 3, 41]])

In [ ]:
device = 'cpu'
X = torch.rand(2, 2).to(device)
Y = torch.rand_like(X).to(device)

Z = 2*torch.ones(2, 2).to(device)

%timeit A = X * Y
%timeit B = Y @ Z
%timeit C = A + B

2.09 µs ± 26.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.7 µs ± 40.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.11 µs ± 38.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [ ]:
device = 'cuda'
X = torch.rand(2, 2).to(device)
Y = torch.rand_like(X).to(device)

Z = 2*torch.ones(2, 2).to(device)

%timeit A = X * Y
%timeit B = Y @ Z
%timeit C = A + B

7.01 µs ± 140 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
9 µs ± 90.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
2.14 µs ± 66.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
